name: toktik
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    # - assets/videos/1.mp4
    # - assets/2.mp4
    # - assets/3.mp4
    # - assets/4.mp4
    # - assets/5.mp4
    # - assets/6.mp4
    # - assets/7.mp4
    # - assets/8.mp4
